#%RAML 1.0
version: v1
title: pii-tokenizer-poc-api

      
/phone_verification:
      displayName: Phone verification
      description: Phone verification
      get:
        responses:
              200:
                